spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tails
    username: root
    password: 123123
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  plugins:
  - com.github.pagehelper.PageInterceptor

aliyun:
  oss:
    endpoint: https://oss-cn-shanghai.aliyuncs.com
    accessKeyId: LTAI5tETyCZy1Q5iXixiEu8E
    accessKeySecret: uHHOet7rzAmo8qjokkAsR1lRlVfFv9
    bucketName: ecust-web-jwq
# spring 事务管理
logging:
  level:
    org.springframwork.jdbc.support.JdbcTransactionManager: debug
